version: "3"
services:
          
    www:
        container_name: "apache-container"
        build: .
        ports:
            - "80:80"
        volumes:
            - ./project:/var/www/html/
        networks:
            - default